apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-test-app
spec:
  scaleTargetRef:
    name: sqs-test-app # Target deployment name
  minReplicaCount: 0  # We don't want pods if the queue is empty
  maxReplicaCount: 5  # We don't want to have more than 5 replicas
  pollingInterval: 10 # How frequently we should go for metrics (in seconds)
  cooldownPeriod:  25 # How many seconds should we wait for downscale  
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-aws-credentials
    metadata:
      queueURL: https://sqs.us-west-2.amazonaws.com/317630533282/keda-test-queue
      queueLength: "2"
      awsRegion: "us-west-2"
      identityOwner: operator
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-credentials
spec:
  podIdentity:
    provider: eks