---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: keda-demo-cluster
    region: us-west-2
iam:
  withOIDC: true
addons:
- name: vpc-cni
  version: latest
  resolveConflicts: overwrite
- name: coredns
  version: latest
  configurationValues: "{\"replicaCount\":3}"
  resolveConflicts: overwrite
- name: kube-proxy
  version: latest
  resolveConflicts: overwrite
# - name: eks-pod-identity-agent
#   version: latest
#   resolveConflicts: overwrite
managedNodeGroups:
    - name: keda-demo-cluster-workers
      labels: { role: workers }
      instanceType: t3.medium
      volumeSize: 100
      privateNetworking: true
      desiredCapacity: 2
      minSize: 1
      maxSize: 4